### ISSUE TITLE
💎support gif fetching

### ISSUE THREAD

**Issue by gabrielstuff** [soixantecircuits/fetch-images#4]
Could just use http://api.giphy.com/v1/gifs/random?api_key=dc6zaTOxFJmzC&tag=dog

See docs here: https://github.com/Giphy/GiphyAPI#random-endpoint

**Comment by negabakuru** [comment]
Done in https://github.com/soixantecircuits/gofetch/commit/1b9e6afd333a33cde759c244a944ff1f27ba2be4
