### ISSUE TITLE
Doesn't work when installed with `npm -g` or when not in the root dir

### ISSUE THREAD

**Issue by PoignardAzur** [soixantecircuits/fetch-images#5]
I followed the install steps in `README.md`.

To be specific, I did:

`npm install -g gofetch`

`gofetch`

Which gave me the following message:

```
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
```

I then did

`git clone https://github.com/soixantecircuits/gofetch.git && npm install`

`node ./gofetch/`

Which gave me the same error. I suspect the error is caused by `standard-settings`; I think it fails silently when not in a directory with a `settings/settings.default.json` file.

**Comment by negabakuru** [comment]
I added default values for gofetch so it should still run even if standard-settings fails

**Comment by negabakuru** [comment]
Here's the issue for standard-settings https://github.com/soixantecircuits/standard-settings/issues/5
